// flow-typed signature: 2dd7bbc6776bb8362728ea84c73a5a58
// flow-typed version: <<STUB>>/list_v0.8.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'list' {
  declare module.exports: any;
}
